const mongoose = require('mongoose');
const Tag = require('../models/Tag');
require('dotenv').config();

const tagData = [
  {
    category: 'זמן הכנה',
    categoryEn: 'Preparation Time',
    tags: [
      {he: 'עד 10 דקות', en: 'Up to 10 minutes', globalId: 'TAG_TIME_10MIN'},
      {he: 'עד 20 דקות', en: 'Up to 20 minutes', globalId: 'TAG_TIME_20MIN'},
      {he: 'עד 30 דקות', en: 'Up to 30 minutes', globalId: 'TAG_TIME_30MIN'},
      {he: 'עד 45 דקות', en: 'Up to 45 minutes', globalId: 'TAG_TIME_45MIN'},
      {he: 'עד שעה', en: 'Up to 1 hour', globalId: 'TAG_TIME_1HOUR'},
      {he: 'עד שעתיים', en: 'Up to 2 hours', globalId: 'TAG_TIME_2HOURS'},
      {he: 'מעל שעתיים', en: 'Over 2 hours', globalId: 'TAG_TIME_2PLUS'},
      {he: 'הכנה מהירה', en: 'Quick prep', globalId: 'TAG_TIME_QUICK'},
      {he: 'הכנה ארוכה', en: 'Long prep', globalId: 'TAG_TIME_LONG'},
    ],
  },
  {
    category: 'רמת קושי',
    categoryEn: 'Difficulty',
    tags: [
      {he: 'קל מאוד', en: 'Very Easy', globalId: 'TAG_DIFF_VERYEASY'},
      {he: 'קל', en: 'Easy', globalId: 'TAG_DIFF_EASY'},
      {he: 'בינוני', en: 'Medium', globalId: 'TAG_DIFF_MEDIUM'},
      {he: 'מתקדם', en: 'Advanced', globalId: 'TAG_DIFF_ADVANCED'},
      {he: 'מקצועי', en: 'Professional', globalId: 'TAG_DIFF_PRO'},
      {he: 'למתחילים', en: 'For beginners', globalId: 'TAG_DIFF_BEGINNER'},
      {he: 'דורש ניסיון', en: 'Requires experience', globalId: 'TAG_DIFF_EXPERT'},
    ],
  },
  {
    category: 'סוג מנה',
    categoryEn: 'Dish Type',
    tags: [
      {he: 'מנה ראשונה', en: 'Appetizer', globalId: 'TAG_DISH_APPETIZER'},
      {he: 'מנה עיקרית', en: 'Main course', globalId: 'TAG_DISH_MAIN'},
      {he: 'קינוח', en: 'Dessert', globalId: 'TAG_DISH_DESSERT'},
      {he: 'חטיף', en: 'Snack', globalId: 'TAG_DISH_SNACK'},
      {he: 'סלט', en: 'Salad', globalId: 'TAG_DISH_SALAD'},
      {he: 'מרק', en: 'Soup', globalId: 'TAG_DISH_SOUP'},
      {he: 'תבשיל', en: 'Stew', globalId: 'TAG_DISH_STEW'},
      {he: 'פשטידה', en: 'Pie', globalId: 'TAG_DISH_PIE'},
      {he: 'קיש', en: 'Quiche', globalId: 'TAG_DISH_QUICHE'},
      {he: 'פיצה', en: 'Pizza', globalId: 'TAG_DISH_PIZZA'},
      {he: 'המבורגר', en: 'Burger', globalId: 'TAG_DISH_BURGER'},
      {he: 'סנדוויץ׳', en: 'Sandwich', globalId: 'TAG_DISH_SANDWICH'},
      {he: 'פסטה', en: 'Pasta', globalId: 'TAG_DISH_PASTA'},
      {he: 'ריזוטו', en: 'Risotto', globalId: 'TAG_DISH_RISOTTO'},
      {he: 'אורז', en: 'Rice', globalId: 'TAG_DISH_RICE'},
      {he: 'לחם', en: 'Bread', globalId: 'TAG_DISH_BREAD'},
      {he: 'עוגה', en: 'Cake', globalId: 'TAG_DISH_CAKE'},
      {he: 'עוגיות', en: 'Cookies', globalId: 'TAG_DISH_COOKIES'},
      {he: 'מאפה', en: 'Pastry', globalId: 'TAG_DISH_PASTRY'},
      {he: 'טארט', en: 'Tart', globalId: 'TAG_DISH_TART'},
    ],
  },
  {
    category: 'תזונה',
    categoryEn: 'Nutrition',
    tags: [
      {he: 'טבעוני', en: 'Vegan', globalId: 'TAG_DIET_VEGAN'},
      {he: 'צמחוני', en: 'Vegetarian', globalId: 'TAG_DIET_VEGETARIAN'},
      {he: 'ללא גלוטן', en: 'Gluten-free', globalId: 'TAG_DIET_GLUTENFREE'},
      {he: 'ללא לקטוז', en: 'Lactose-free', globalId: 'TAG_DIET_LACTOSEFREE'},
      {he: 'דל פחמימות', en: 'Low carb', globalId: 'TAG_DIET_LOWCARB'},
      {he: 'דל שומן', en: 'Low fat', globalId: 'TAG_DIET_LOWFAT'},
      {he: 'דל קלוריות', en: 'Low calorie', globalId: 'TAG_DIET_LOWCAL'},
      {he: 'עתיר חלבון', en: 'High protein', globalId: 'TAG_DIET_HIGHPROTEIN'},
      {he: 'קטוגני', en: 'Keto', globalId: 'TAG_DIET_KETO'},
      {he: 'פליאו', en: 'Paleo', globalId: 'TAG_DIET_PALEO'},
      {he: 'ללא סוכר', en: 'Sugar-free', globalId: 'TAG_DIET_SUGARFREE'},
      {he: 'אורגני', en: 'Organic', globalId: 'TAG_DIET_ORGANIC'},
      {he: 'ללא חומרים מלאכותיים', en: 'No artificial', globalId: 'TAG_DIET_NOARTIFICIAL'},
      {he: 'ללא אגוזים', en: 'Nut-free', globalId: 'TAG_DIET_NUTFREE'},
      {he: 'ללא סויה', en: 'Soy-free', globalId: 'TAG_DIET_SOYFREE'},
    ],
  },
  {
    category: 'כשרות',
    categoryEn: 'Kosher',
    tags: [
      {he: 'כשר', en: 'Kosher', globalId: 'TAG_KOSHER_YES'},
      {he: 'כשר למהדרין', en: 'Kosher Mehadrin', globalId: 'TAG_KOSHER_MEHADRIN'},
      {he: 'פרווה', en: 'Pareve', globalId: 'TAG_KOSHER_PAREVE'},
      {he: 'חלבי', en: 'Dairy', globalId: 'TAG_KOSHER_DAIRY'},
      {he: 'בשרי', en: 'Meat', globalId: 'TAG_KOSHER_MEAT'},
      {he: 'כשר לפסח', en: 'Kosher for Passover', globalId: 'TAG_KOSHER_PASSOVER'},
    ],
  },
  {
    category: 'סגנון מטבח',
    categoryEn: 'Cuisine Style',
    tags: [
      {he: 'איטלקי', en: 'Italian', globalId: 'TAG_CUISINE_ITALIAN'},
      {he: 'צרפתי', en: 'French', globalId: 'TAG_CUISINE_FRENCH'},
      {he: 'ספרדי', en: 'Spanish', globalId: 'TAG_CUISINE_SPANISH'},
      {he: 'יווני', en: 'Greek', globalId: 'TAG_CUISINE_GREEK'},
      {he: 'תורכי', en: 'Turkish', globalId: 'TAG_CUISINE_TURKISH'},
      {he: 'מרוקאי', en: 'Moroccan', globalId: 'TAG_CUISINE_MOROCCAN'},
      {he: 'תימני', en: 'Yemenite', globalId: 'TAG_CUISINE_YEMENITE'},
      {he: 'אתיופי', en: 'Ethiopian', globalId: 'TAG_CUISINE_ETHIOPIAN'},
      {he: 'הודי', en: 'Indian', globalId: 'TAG_CUISINE_INDIAN'},
      {he: 'תאילנדי', en: 'Thai', globalId: 'TAG_CUISINE_THAI'},
      {he: 'סיני', en: 'Chinese', globalId: 'TAG_CUISINE_CHINESE'},
      {he: 'יפני', en: 'Japanese', globalId: 'TAG_CUISINE_JAPANESE'},
      {he: 'קוריאני', en: 'Korean', globalId: 'TAG_CUISINE_KOREAN'},
      {he: 'וייטנאמי', en: 'Vietnamese', globalId: 'TAG_CUISINE_VIETNAMESE'},
      {he: 'מקסיקני', en: 'Mexican', globalId: 'TAG_CUISINE_MEXICAN'},
      {he: 'אמריקאי', en: 'American', globalId: 'TAG_CUISINE_AMERICAN'},
      {he: 'ישראלי', en: 'Israeli', globalId: 'TAG_CUISINE_ISRAELI'},
      {he: 'ים תיכוני', en: 'Mediterranean', globalId: 'TAG_CUISINE_MEDITERRANEAN'},
      {he: 'מזרח תיכוני', en: 'Middle Eastern', globalId: 'TAG_CUISINE_MIDDLEEASTERN'},
      {he: 'אסייתי', en: 'Asian', globalId: 'TAG_CUISINE_ASIAN'},
      {he: 'לטיני', en: 'Latin', globalId: 'TAG_CUISINE_LATIN'},
      {he: 'בלקני', en: 'Balkan', globalId: 'TAG_CUISINE_BALKAN'},
      {he: 'רוסי', en: 'Russian', globalId: 'TAG_CUISINE_RUSSIAN'},
      {he: 'פולני', en: 'Polish', globalId: 'TAG_CUISINE_POLISH'},
      {he: 'הונגרי', en: 'Hungarian', globalId: 'TAG_CUISINE_HUNGARIAN'},
      {he: 'ברזילאי', en: 'Brazilian', globalId: 'TAG_CUISINE_BRAZILIAN'},
      {he: 'ארגנטינאי', en: 'Argentinian', globalId: 'TAG_CUISINE_ARGENTINIAN'},
    ],
  },
  {
    category: 'חומרי גלם',
    categoryEn: 'Ingredients',
    tags: [
      {he: 'בשר בקר', en: 'Beef', globalId: 'TAG_INGRED_BEEF'},
      {he: 'עוף', en: 'Chicken', globalId: 'TAG_INGRED_CHICKEN'},
      {he: 'הודו', en: 'Turkey', globalId: 'TAG_INGRED_TURKEY'},
      {he: 'כבש', en: 'Lamb', globalId: 'TAG_INGRED_LAMB'},
      {he: 'דגים', en: 'Fish', globalId: 'TAG_INGRED_FISH'},
      {he: 'פירות ים', en: 'Seafood', globalId: 'TAG_INGRED_SEAFOOD'},
      {he: 'ביצים', en: 'Eggs', globalId: 'TAG_INGRED_EGGS'},
      {he: 'חלב', en: 'Milk', globalId: 'TAG_INGRED_MILK'},
      {he: 'גבינה', en: 'Cheese', globalId: 'TAG_INGRED_CHEESE'},
      {he: 'יוגורט', en: 'Yogurt', globalId: 'TAG_INGRED_YOGURT'},
      {he: 'שמנת', en: 'Cream', globalId: 'TAG_INGRED_CREAM'},
      {he: 'חמאה', en: 'Butter', globalId: 'TAG_INGRED_BUTTER'},
      {he: 'ירקות', en: 'Vegetables', globalId: 'TAG_INGRED_VEGETABLES'},
      {he: 'פירות', en: 'Fruits', globalId: 'TAG_INGRED_FRUITS'},
      {he: 'קטניות', en: 'Legumes', globalId: 'TAG_INGRED_LEGUMES'},
      {he: 'אגוזים', en: 'Nuts', globalId: 'TAG_INGRED_NUTS'},
      {he: 'זרעים', en: 'Seeds', globalId: 'TAG_INGRED_SEEDS'},
      {he: 'דגנים', en: 'Grains', globalId: 'TAG_INGRED_GRAINS'},
      {he: 'קמח', en: 'Flour', globalId: 'TAG_INGRED_FLOUR'},
      {he: 'אורז', en: 'Rice', globalId: 'TAG_INGRED_RICE'},
      {he: 'פסטה', en: 'Pasta', globalId: 'TAG_INGRED_PASTA'},
      {he: 'תפוחי אדמה', en: 'Potatoes', globalId: 'TAG_INGRED_POTATOES'},
      {he: 'בטטה', en: 'Sweet potato', globalId: 'TAG_INGRED_SWEETPOTATO'},
      {he: 'עגבניות', en: 'Tomatoes', globalId: 'TAG_INGRED_TOMATOES'},
      {he: 'שום', en: 'Garlic', globalId: 'TAG_INGRED_GARLIC'},
      {he: 'בצל', en: 'Onion', globalId: 'TAG_INGRED_ONION'},
      {he: 'פלפלים', en: 'Peppers', globalId: 'TAG_INGRED_PEPPERS'},
      {he: 'שוקולד', en: 'Chocolate', globalId: 'TAG_INGRED_CHOCOLATE'},
    ],
  },
  {
    category: 'שיטת בישול',
    categoryEn: 'Cooking Method',
    tags: [
      {he: 'אפייה', en: 'Baking', globalId: 'TAG_METHOD_BAKING'},
      {he: 'צלייה', en: 'Roasting', globalId: 'TAG_METHOD_ROASTING'},
      {he: 'טיגון', en: 'Frying', globalId: 'TAG_METHOD_FRYING'},
      {he: 'טיגון עמוק', en: 'Deep frying', globalId: 'TAG_METHOD_DEEPFRYING'},
      {he: 'בישול', en: 'Boiling', globalId: 'TAG_METHOD_BOILING'},
      {he: 'אידוי', en: 'Steaming', globalId: 'TAG_METHOD_STEAMING'},
      {he: 'צלייה בגריל', en: 'Grilling', globalId: 'TAG_METHOD_GRILLING'},
      {he: 'הקצפה', en: 'Whipping', globalId: 'TAG_METHOD_WHIPPING'},
      {he: 'סיר לחץ', en: 'Pressure cooker', globalId: 'TAG_METHOD_PRESSURECOOKER'},
      {he: 'סיר איטי', en: 'Slow cooker', globalId: 'TAG_METHOD_SLOWCOOKER'},
      {he: 'מיקרוגל', en: 'Microwave', globalId: 'TAG_METHOD_MICROWAVE'},
      {he: 'ללא חום', en: 'No-cook', globalId: 'TAG_METHOD_NOCOOK'},
      {he: 'ללא אפייה', en: 'No-bake', globalId: 'TAG_METHOD_NOBAKE'},
      {he: 'סוס ויד', en: 'Sous vide', globalId: 'TAG_METHOD_SOUSVIDE'},
      {he: 'מעשן', en: 'Smoking', globalId: 'TAG_METHOD_SMOKING'},
      {he: 'מסיר', en: 'Marinating', globalId: 'TAG_METHOD_MARINATING'},
    ],
  },
  {
    category: 'עונות שנה',
    categoryEn: 'Seasons',
    tags: [
      {he: 'אביב', en: 'Spring', globalId: 'TAG_SEASON_SPRING'},
      {he: 'קיץ', en: 'Summer', globalId: 'TAG_SEASON_SUMMER'},
      {he: 'סתיו', en: 'Autumn', globalId: 'TAG_SEASON_AUTUMN'},
      {he: 'חורף', en: 'Winter', globalId: 'TAG_SEASON_WINTER'},
      {he: 'כל השנה', en: 'Year-round', globalId: 'TAG_SEASON_ALLYEAR'},
    ],
  },
  {
    category: 'חגים',
    categoryEn: 'Holidays',
    tags: [
      {he: 'ראש השנה', en: 'Rosh Hashanah', globalId: 'TAG_HOLIDAY_ROSHHASHANAH'},
      {he: 'יום כיפור', en: 'Yom Kippur', globalId: 'TAG_HOLIDAY_YOMKIPPUR'},
      {he: 'סוכות', en: 'Sukkot', globalId: 'TAG_HOLIDAY_SUKKOT'},
      {he: 'חנוכה', en: 'Hanukkah', globalId: 'TAG_HOLIDAY_HANUKKAH'},
      {he: 'טו בשבט', en: 'Tu BiShvat', globalId: 'TAG_HOLIDAY_TUBISHVAT'},
      {he: 'פורים', en: 'Purim', globalId: 'TAG_HOLIDAY_PURIM'},
      {he: 'פסח', en: 'Passover', globalId: 'TAG_HOLIDAY_PASSOVER'},
      {he: 'יום העצמאות', en: 'Independence Day', globalId: 'TAG_HOLIDAY_INDEPENDENCE'},
      {he: 'לג בעומר', en: 'Lag BaOmer', globalId: 'TAG_HOLIDAY_LAGBAOMER'},
      {he: 'שבועות', en: 'Shavuot', globalId: 'TAG_HOLIDAY_SHAVUOT'},
      {he: 'תשעה באב', en: 'Tisha BAv', globalId: 'TAG_HOLIDAY_TISHABAAV'},
      {he: 'שבת', en: 'Shabbat', globalId: 'TAG_HOLIDAY_SHABBAT'},
      {he: 'ערב חג', en: 'Holiday eve', globalId: 'TAG_HOLIDAY_EVE'},
    ],
  },
  {
    category: 'אירועים',
    categoryEn: 'Events',
    tags: [
      {he: 'יום הולדת', en: 'Birthday', globalId: 'TAG_EVENT_BIRTHDAY'},
      {he: 'חתונה', en: 'Wedding', globalId: 'TAG_EVENT_WEDDING'},
      {he: 'בר/בת מצווה', en: 'Bar/Bat Mitzvah', globalId: 'TAG_EVENT_BARMITZVAH'},
      {he: 'ברית', en: 'Brit', globalId: 'TAG_EVENT_BRIT'},
      {he: 'פיקניק', en: 'Picnic', globalId: 'TAG_EVENT_PICNIC'},
      {he: 'ברביקיו', en: 'BBQ', globalId: 'TAG_EVENT_BBQ'},
      {he: 'מסיבה', en: 'Party', globalId: 'TAG_EVENT_PARTY'},
      {he: 'ארוחה משפחתית', en: 'Family dinner', globalId: 'TAG_EVENT_FAMILYDINNER'},
      {he: 'ארוחה רומנטית', en: 'Romantic dinner', globalId: 'TAG_EVENT_ROMANTIC'},
      {he: 'מפגש חברים', en: 'Friends gathering', globalId: 'TAG_EVENT_FRIENDS'},
      {he: 'פוטלאק', en: 'Potluck', globalId: 'TAG_EVENT_POTLUCK'},
      {he: 'טיול', en: 'Trip', globalId: 'TAG_EVENT_TRIP'},
    ],
  },
  {
    category: 'ארוחות ביום',
    categoryEn: 'Daily Meals',
    tags: [
      {he: 'ארוחת בוקר', en: 'Breakfast', globalId: 'TAG_MEAL_BREAKFAST'},
      {he: 'בראנץ׳', en: 'Brunch', globalId: 'TAG_MEAL_BRUNCH'},
      {he: 'ארוחת צהריים', en: 'Lunch', globalId: 'TAG_MEAL_LUNCH'},
      {he: 'ארוחת ערב', en: 'Dinner', globalId: 'TAG_MEAL_DINNER'},
      {he: 'חטיף בין ארוחות', en: 'Snack', globalId: 'TAG_MEAL_SNACK'},
      {he: 'קינוח', en: 'Dessert', globalId: 'TAG_MEAL_DESSERT'},
      {he: 'משקה', en: 'Drink', globalId: 'TAG_MEAL_DRINK'},
      {he: 'שייק', en: 'Smoothie', globalId: 'TAG_MEAL_SMOOTHIE'},
      {he: 'מיץ', en: 'Juice', globalId: 'TAG_MEAL_JUICE'},
      {he: 'קפה', en: 'Coffee', globalId: 'TAG_MEAL_COFFEE'},
      {he: 'תה', en: 'Tea', globalId: 'TAG_MEAL_TEA'},
    ],
  },
  {
    category: 'מרקמים',
    categoryEn: 'Textures',
    tags: [
      {he: 'פריך', en: 'Crispy', globalId: 'TAG_TEXTURE_CRISPY'},
      {he: 'קריספי', en: 'Crunchy', globalId: 'TAG_TEXTURE_CRUNCHY'},
      {he: 'רך', en: 'Soft', globalId: 'TAG_TEXTURE_SOFT'},
      {he: 'קרמי', en: 'Creamy', globalId: 'TAG_TEXTURE_CREAMY'},
      {he: 'עסיסי', en: 'Juicy', globalId: 'TAG_TEXTURE_JUICY'},
      {he: 'לח', en: 'Moist', globalId: 'TAG_TEXTURE_MOIST'},
      {he: 'פריך בחוץ רך בפנים', en: 'Crispy outside soft inside', globalId: 'TAG_TEXTURE_CRISPYSOFT'},
      {he: 'גומי', en: 'Chewy', globalId: 'TAG_TEXTURE_CHEWY'},
      {he: 'נימוח', en: 'Melting', globalId: 'TAG_TEXTURE_MELTING'},
      {he: 'אוורירי', en: 'Fluffy', globalId: 'TAG_TEXTURE_FLUFFY'},
      {he: 'צפוף', en: 'Dense', globalId: 'TAG_TEXTURE_DENSE'},
    ],
  },
  {
    category: 'טעמים',
    categoryEn: 'Flavors',
    tags: [
      {he: 'מתוק', en: 'Sweet', globalId: 'TAG_TASTE_SWEET'},
      {he: 'מלוח', en: 'Salty', globalId: 'TAG_TASTE_SALTY'},
      {he: 'חמוץ', en: 'Sour', globalId: 'TAG_TASTE_SOUR'},
      {he: 'מר', en: 'Bitter', globalId: 'TAG_TASTE_BITTER'},
      {he: 'אומאמי', en: 'Umami', globalId: 'TAG_TASTE_UMAMI'},
      {he: 'חריף', en: 'Spicy', globalId: 'TAG_TASTE_SPICY'},
      {he: 'חריף מאוד', en: 'Very spicy', globalId: 'TAG_TASTE_VERYSPICY'},
      {he: 'מתוק-חמוץ', en: 'Sweet-sour', globalId: 'TAG_TASTE_SWEETSOUR'},
      {he: 'מלוח-מתוק', en: 'Salty-sweet', globalId: 'TAG_TASTE_SALTYSWEET'},
      {he: 'עשיר', en: 'Rich', globalId: 'TAG_TASTE_RICH'},
      {he: 'עדין', en: 'Delicate', globalId: 'TAG_TASTE_DELICATE'},
      {he: 'עוצמתי', en: 'Intense', globalId: 'TAG_TASTE_INTENSE'},
      {he: 'ניטרלי', en: 'Neutral', globalId: 'TAG_TASTE_NEUTRAL'},
      {he: 'מעושן', en: 'Smoky', globalId: 'TAG_TASTE_SMOKY'},
      {he: 'מתובל', en: 'Spiced', globalId: 'TAG_TASTE_SPICED'},
      {he: 'ארומטי', en: 'Aromatic', globalId: 'TAG_TASTE_AROMATIC'},
    ],
  },
  {
    category: 'תקציב',
    categoryEn: 'Budget',
    tags: [
      {he: 'זול', en: 'Cheap', globalId: 'TAG_BUDGET_CHEAP'},
      {he: 'חסכוני', en: 'Budget-friendly', globalId: 'TAG_BUDGET_FRIENDLY'},
      {he: 'בינוני', en: 'Moderate', globalId: 'TAG_BUDGET_MODERATE'},
      {he: 'יקר', en: 'Expensive', globalId: 'TAG_BUDGET_EXPENSIVE'},
      {he: 'יוקרתי', en: 'Luxury', globalId: 'TAG_BUDGET_LUXURY'},
      {he: 'שווה כסף', en: 'Value for money', globalId: 'TAG_BUDGET_VALUE'},
    ],
  },
  {
    category: 'כלי בישול',
    categoryEn: 'Cooking Tools',
    tags: [
      {he: 'סיר אחד', en: 'One pot', globalId: 'TAG_TOOL_ONEPOT'},
      {he: 'תבנית אחת', en: 'One pan', globalId: 'TAG_TOOL_ONEPAN'},
      {he: 'ללא תנור', en: 'No oven', globalId: 'TAG_TOOL_NOOVEN'},
      {he: 'תנור בלבד', en: 'Oven only', globalId: 'TAG_TOOL_OVENONLY'},
      {he: 'גריל', en: 'Grill', globalId: 'TAG_TOOL_GRILL'},
      {he: 'מחבת', en: 'Pan', globalId: 'TAG_TOOL_PAN'},
      {he: 'סיר', en: 'Pot', globalId: 'TAG_TOOL_POT'},
      {he: 'תבנית אפייה', en: 'Baking sheet', globalId: 'TAG_TOOL_BAKINGSHEET'},
      {he: 'מיקסר', en: 'Mixer', globalId: 'TAG_TOOL_MIXER'},
      {he: 'בלנדר', en: 'Blender', globalId: 'TAG_TOOL_BLENDER'},
      {he: 'מעבד מזון', en: 'Food processor', globalId: 'TAG_TOOL_FOODPROCESSOR'},
      {he: 'סיר לחץ', en: 'Pressure cooker', globalId: 'TAG_TOOL_PRESSURECOOKER2'},
      {he: 'מחבת ווק', en: 'Wok', globalId: 'TAG_TOOL_WOK'},
    ],
  },
  {
    category: 'בריאות',
    categoryEn: 'Health',
    tags: [
      {he: 'בריא', en: 'Healthy', globalId: 'TAG_HEALTH_HEALTHY'},
      {he: 'מזין', en: 'Nutritious', globalId: 'TAG_HEALTH_NUTRITIOUS'},
      {he: 'דל קלוריות', en: 'Low calorie', globalId: 'TAG_HEALTH_LOWCAL'},
      {he: 'דל שומן', en: 'Low fat', globalId: 'TAG_HEALTH_LOWFAT'},
      {he: 'דל פחמימות', en: 'Low carb', globalId: 'TAG_HEALTH_LOWCARB'},
      {he: 'עתיר חלבון', en: 'High protein', globalId: 'TAG_HEALTH_HIGHPROTEIN'},
      {he: 'עתיר סיבים', en: 'High fiber', globalId: 'TAG_HEALTH_HIGHFIBER'},
      {he: 'נוגד חמצון', en: 'Antioxidant', globalId: 'TAG_HEALTH_ANTIOXIDANT'},
      {he: 'מגביר חיסון', en: 'Immune boost', globalId: 'TAG_HEALTH_IMMUNEBOOST'},
      {he: 'טוב ללב', en: 'Heart healthy', globalId: 'TAG_HEALTH_HEARTHEALTHY'},
      {he: 'לירידה במשקל', en: 'Weight loss', globalId: 'TAG_HEALTH_WEIGHTLOSS'},
      {he: 'לעלייה במסת שריר', en: 'Muscle gain', globalId: 'TAG_HEALTH_MUSCLEGAIN'},
      {he: 'אנרגטי', en: 'Energizing', globalId: 'TAG_HEALTH_ENERGIZING'},
      {he: 'מרגיע', en: 'Calming', globalId: 'TAG_HEALTH_CALMING'},
      {he: 'דטוקס', en: 'Detox', globalId: 'TAG_HEALTH_DETOX'},
    ],
  },
  {
    category: 'לילדים',
    categoryEn: 'For Kids',
    tags: [
      {he: 'ידידותי לילדים', en: 'Kid-friendly', globalId: 'TAG_KIDS_FRIENDLY'},
      {he: 'לילדים פעוטות', en: 'For toddlers', globalId: 'TAG_KIDS_TODDLERS'},
      {he: 'ארוחה לילדים', en: 'Kids meal', globalId: 'TAG_KIDS_MEAL'},
      {he: 'חטיף לבית הספר', en: 'School snack', globalId: 'TAG_KIDS_SCHOOLSNACK'},
      {he: 'מזון לתינוקות', en: 'Baby food', globalId: 'TAG_KIDS_BABYFOOD'},
      {he: 'כיף להכין עם ילדים', en: 'Fun to make with kids', globalId: 'TAG_KIDS_FUNTOMAKE'},
      {he: 'צבעוני ומושך', en: 'Colorful and appealing', globalId: 'TAG_KIDS_COLORFUL'},
    ],
  },
  {
    category: 'מקור המתכון',
    categoryEn: 'Recipe Source',
    tags: [
      {he: 'מסורתי', en: 'Traditional', globalId: 'TAG_SOURCE_TRADITIONAL'},
      {he: 'משפחתי', en: 'Family recipe', globalId: 'TAG_SOURCE_FAMILY'},
      {he: 'מקורי', en: 'Original', globalId: 'TAG_SOURCE_ORIGINAL'},
      {he: 'מותאם', en: 'Adapted', globalId: 'TAG_SOURCE_ADAPTED'},
      {he: 'מודרני', en: 'Modern', globalId: 'TAG_SOURCE_MODERN'},
      {he: 'פיוזן', en: 'Fusion', globalId: 'TAG_SOURCE_FUSION'},
      {he: 'קלאסי', en: 'Classic', globalId: 'TAG_SOURCE_CLASSIC'},
      {he: 'חדשני', en: 'Innovative', globalId: 'TAG_SOURCE_INNOVATIVE'},
      {he: 'מסעדתי', en: 'Restaurant style', globalId: 'TAG_SOURCE_RESTAURANT'},
      {he: 'ביתי', en: 'Homestyle', globalId: 'TAG_SOURCE_HOMESTYLE'},
      {he: 'של סבתא', en: 'Grandmas recipe', globalId: 'TAG_SOURCE_GRANDMA'},
    ],
  },
  {
    category: 'תוספות ליד',
    categoryEn: 'Side Dishes',
    tags: [
      {he: 'עם אורז', en: 'With rice', globalId: 'TAG_SIDE_RICE'},
      {he: 'עם פסטה', en: 'With pasta', globalId: 'TAG_SIDE_PASTA'},
      {he: 'עם לחם', en: 'With bread', globalId: 'TAG_SIDE_BREAD'},
      {he: 'עם פיתה', en: 'With pita', globalId: 'TAG_SIDE_PITA'},
      {he: 'עם סלט', en: 'With salad', globalId: 'TAG_SIDE_SALAD'},
      {he: 'עם ירקות', en: 'With vegetables', globalId: 'TAG_SIDE_VEGETABLES'},
      {he: 'עם תפוחי אדמה', en: 'With potatoes', globalId: 'TAG_SIDE_POTATOES'},
      {he: 'עם צ׳יפס', en: 'With fries', globalId: 'TAG_SIDE_FRIES'},
      {he: 'עם קוסקוס', en: 'With couscous', globalId: 'TAG_SIDE_COUSCOUS'},
      {he: 'עם פורה', en: 'With mash', globalId: 'TAG_SIDE_MASH'},
      {he: 'עם רוטב', en: 'With sauce', globalId: 'TAG_SIDE_SAUCE'},
    ],
  },
];

async function seedTags() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log('Connected to MongoDB');

    // Clear existing tags
    await Tag.deleteMany({});
    console.log('Cleared existing tags');

    // Insert new tags
    const result = await Tag.insertMany(tagData);
    console.log(`Successfully seeded ${result.length} tag categories`);

    // Count total tags
    const totalTags = result.reduce((sum, cat) => sum + cat.tags.length, 0);
    console.log(`Total tags: ${totalTags}`);

    mongoose.connection.close();
    console.log('Database connection closed');
  } catch (error) {
    console.error('Error seeding tags:', error);
    process.exit(1);
  }
}

seedTags();
